version: "3.3"

networks:
  web-network:


services:
  php-server:
    image: namoshek/php-mssql:8.2-fpm-alpine
    container_name: php-server
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    networks:
      - web-network

  app-server:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: app-server
    ports:
      - "8080:80"
    volumes:
      - "./html/:/var/www/html/"
    depends_on:
      - php-server
    networks:
      - web-network
